Fix the program to run without `panic!` on a completely fresh environment.
The problem before these changes:
From a blank install (just learned about this program), just running `settle` causes the binary to panic. At first:

```
thread 'main' panicked at 'Unable to write file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/settle-0.38.0/src/io.rs:34:23
```

line 34 in io.rs calls to line 62 in config.rs:
`write_to_file(&config_path, &data);`

solution: handle the directory first, by having `config_path` refer to the dir, and add `config_file` to refer to the .yaml. Then, add a check to make sure the dir exists, and create it if it doesn't using the already-written `mkdir`.

next problem:
`    let result = match path.chars().next().unwrap() {`

line 31 of config.rs calls `next()` before doing anything on the `&str` - since the default in the code is the empty string "", the subsequent `.unwrap()` causes a panic

solution: not entirely clear; I just added this block to the very front of `expand_path`:
```
    if path.chars().count() < 1 {
        return path.to_string();
    }
```

This change made the program exit cleanly when just invoking it with `cargo run`, but I'm not sure that this is the best solution.

Finally, some of the `use`s have been reordered; my editor setup automatically runs `rustfmt`. I removed a lot of the things this changed to avoid noise, but left the `use` re-orders for lines where I added an import. I do recommend running `rustfmt` across your code automatically somehow, but I'll leave that up to you as the author.